/**
 * Demo dataset — all Tadawul main-market listed companies.
 * Reports are placeholder entries (no real files); clicking them is disabled in the UI.
 * Real uploaded reports from Supabase are merged on top of this list at runtime.
 */

import {
  Building2,
  Landmark,
  Zap,
  FlaskConical,
  ShoppingCart,
  Utensils,
  HeartPulse,
  Shield,
  Truck,
  Home,
  BarChart3,
  Tv,
  Leaf,
  Wifi,
  Package,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type MockReport = {
  id: string;
  fiscal_year: string;
  title: string;
  isPlaceholder: true;
};

export type MockCompany = {
  id: string;
  name_en: string;
  name_ar: string;
  sector: string;
  ticker: string;
  logo_url: string | null;
  reports: MockReport[];
};

// Sector → Lucide icon
export const SECTOR_ICON: Record<string, LucideIcon> = {
  Banks: Landmark,
  'Capital Goods': Package,
  'Commercial & Professional Svc': Building2,
  'Consumer Discretionary Distribution & Retail': ShoppingCart,
  'Consumer Durables & Apparel': ShoppingCart,
  'Consumer Services': Utensils,
  'Consumer Staples Distribution & Retail': ShoppingCart,
  Energy: Zap,
  'Financial Services': BarChart3,
  'Food & Beverages': Utensils,
  'Health Care Equipment & Svc': HeartPulse,
  'Household & Personal Products': Leaf,
  Insurance: Shield,
  Materials: FlaskConical,
  'Media and Entertainment': Tv,
  'Pharma, Biotech & Life Sciences': HeartPulse,
  REITs: Home,
  "Real Estate Mgmt & Dev't": Home,
  'Software & Services': BarChart3,
  'Telecommunication Services': Wifi,
  Transportation: Truck,
  Utilities: Zap,
};

// icon.horse — returns 256×256 icons, free, no auth required
const LOGO_DOMAINS: Record<string, string> = {
  // Banks (shown first on the page)
  RIBL: 'riyadbank.com',
  BJAZ: 'bankaljazira.com',
  SAIB: 'saib.com.sa',
  BSF: 'alfransi.com.sa',
  SAB: 'sab.com',
  ANB: 'anb.com.sa',
  ALRAJHI: 'alrajhibank.com.sa',
  ALBILAD: 'bankalbilad.com.sa',
  ALINMA: 'alinma.com',
  SNB: 'alahli.com',
  // Energy
  'SAUDI ARAMCO': 'aramco.com',
  'PETRO RABIGH': 'petrorabigh.com.sa',
  BAHRI: 'bahri.com.sa',
  // Materials
  SABIC: 'sabic.com',
  MAADEN: 'maaden.com.sa',
  YANSAB: 'yansab.com.sa',
  SIPCHEM: 'sipchem.com',
  TASNEE: 'tasnee.com',
  // Telecom
  STC: 'stc.com.sa',
  'ETIHAD ETISALAT': 'mobily.com.sa',
  'ZAIN KSA': 'sa.zain.com',
  // Food & Beverages
  ALMARAI: 'almarai.com',
  SAVOLA: 'savola.com',
  // Retail
  JARIR: 'jarir.com',
  EXTRA: 'extra.com.sa',
  BINDAWOOD: 'bindawood.com.sa',
  NAHDI: 'nahdi.sa',
  ALDAWAA: 'aldawaamedical.com',
  // Insurance
  'BUPA ARABIA': 'bupa.com.sa',
  TAWUNIYA: 'tawuniya.com.sa',
  // Healthcare
  MOUWASAT: 'mouwasat.com',
  'DALLAH HEALTH': 'dallah-hospital.com',
  'SULAIMAN ALHABIB': 'hmg.com.sa',
  // Utilities
  ACWA: 'acwapower.com',
  // Software
  ELM: 'elm.sa',
  // Financial
  'TADAWUL GROUP': 'saudiexchange.sa',
  KINGDOM: 'kingdom.com.sa',
  // Consumer
  AMERICANA: 'americana-group.com',
  SASCO: 'sasco.com.sa',
};

function logoUrl(ticker: string): string | null {
  const domain = LOGO_DOMAINS[ticker];
  if (domain) return `https://icon.horse/icon/${domain}`;
  return null;
}

function placeholderReports(companyId: string): MockReport[] {
  return [2024, 2023, 2022].map((year) => ({
    id: `mock-${companyId}-${year}`,
    fiscal_year: String(year),
    title: `Annual Report ${year}`,
    isPlaceholder: true as const,
  }));
}

type RawEntry = [string, string, string, string, string?]; // [ticker, name_en, name_ar, sector, logoOverride?]

const RAW: RawEntry[] = [
  // Banks
  ['RIBL', 'Riyad Bank', 'بنك الرياض', 'Banks'],
  ['BJAZ', 'Bank AlJazira', 'بنك الجزيرة', 'Banks'],
  ['SAIB', 'Saudi Investment Bank', 'البنك السعودي للاستثمار', 'Banks'],
  ['BSF', 'Banque Saudi Fransi', 'البنك السعودي الفرنسي', 'Banks'],
  ['SAB', 'Saudi Awwal Bank', 'البنك الأول', 'Banks'],
  ['ANB', 'Arab National Bank', 'البنك العربي الوطني', 'Banks'],
  ['ALRAJHI', 'Al Rajhi Bank', 'مصرف الراجحي', 'Banks'],
  ['ALBILAD', 'Bank AlBilad', 'بنك البلاد', 'Banks'],
  ['ALINMA', 'Alinma Bank', 'مصرف الإنماء', 'Banks'],
  ['SNB', 'Saudi National Bank', 'البنك الأهلي السعودي', 'Banks'],
  // Capital Goods
  ['ASTRA INDUSTRIAL', 'Astra Industrial Group', 'مجموعة أسترا الصناعية', 'Capital Goods'],
  ['SHAKER', 'Al-Hassan Ghazi Ibrahim Shaker', 'شركة الحسن غازي إبراهيم شاكر', 'Capital Goods'],
  ['BAWAN', 'Bawan Company', 'شركة باون', 'Capital Goods'],
  ['EIC', 'Eastern Industrial Company', 'الشركة الشرقية للصناعة', 'Capital Goods'],
  ['SAUDI CERAMICS', 'Saudi Ceramics', 'السيراميك السعودي', 'Capital Goods'],
  ['SAUDI CABLE', 'Saudi Cable Company', 'شركة الكابلات السعودية', 'Capital Goods'],
  ['AMIANTIT', 'Amiantit', 'أميانتيت', 'Capital Goods'],
  ['ALBABTAIN', 'Al Babtain Power & Telecom', 'البابطين للطاقة والاتصالات', 'Capital Goods'],
  ['MESC', 'Middle East Specialized Cables', 'الشركة الأوسطية للكابلات المتخصصة', 'Capital Goods'],
  ['BATIC', 'Batic Investments & Logistics', 'باتك للاستثمارات والخدمات اللوجستية', 'Capital Goods'],
  ['SIECO', 'Saudi Industrial Export Company', 'شركة التصدير الصناعي السعودي', 'Capital Goods'],
  ['ALOMRAN', 'Al-Omran Industrial Trading', 'العمران للتجارة الصناعية', 'Capital Goods'],
  ['RIYADH CABLES', 'Riyadh Cables Group', 'مجموعة كابلات الرياض', 'Capital Goods'],
  ['RAOOM', 'Raoom Trading Company', 'شركة رووم التجارية', 'Capital Goods'],
  ['OGC', 'Obeikan Glass Company', 'شركة عبيكان للزجاج', 'Capital Goods'],
  ['GAS', 'Gas Arabian Services', 'خدمات الغاز العربية', 'Capital Goods'],
  ['CGS', 'Construction Products Holding', 'القابضة لمنتجات البناء', 'Capital Goods'],
  ['ALWASAIL INDUSTRIAL', 'Alwasail Industrial Company', 'شركة الوسائل الصناعية', 'Capital Goods'],
  // Commercial & Professional Svc
  ['MAHARAH', 'Maharah Human Resources', 'مهارة للموارد البشرية', 'Commercial & Professional Svc'],
  ['SADR', 'Sadr Logistics', 'صدر للخدمات اللوجستية', 'Commercial & Professional Svc'],
  ['ALMAWARID', 'Al Mawarid Manpower', 'الموارد للقوى العاملة', 'Commercial & Professional Svc'],
  ['SMASCO', 'Saudi Manpower Solutions', 'سماسكو للحلول الوظيفية', 'Commercial & Professional Svc'],
  ['TAMKEEN', 'Tamkeen Human Resources', 'تمكين للموارد البشرية', 'Commercial & Professional Svc'],
  ['SPPC', 'Saudi Printing & Packaging', 'السعودية للطباعة والتغليف', 'Commercial & Professional Svc'],
  ['CATRION', 'Catrion Catering Holding', 'كترة القابضة للتموين', 'Commercial & Professional Svc'],
  // Consumer Discretionary Distribution & Retail
  ['EXTRA', 'Extra (United Electronics)', 'إكسترا (الإلكترونيات المتحدة)', 'Consumer Discretionary Distribution & Retail'],
  ['SACO', 'SACO', 'ساكو', 'Consumer Discretionary Distribution & Retail'],
  ['SASCO', 'Saudi Automotive Services', 'ساسكو للخدمات التجارية', 'Consumer Discretionary Distribution & Retail'],
  ['BAAZEEM', 'Baazeem Trading', 'بازيم التجارية', 'Consumer Discretionary Distribution & Retail'],
  ['JARIR', 'Jarir Marketing', 'جرير للتسويق', 'Consumer Discretionary Distribution & Retail'],
  ['ABO MOATI', 'Abo Moati Group', 'مجموعة أبو معطي', 'Consumer Discretionary Distribution & Retail'],
  ['ALSAIF GALLERY', 'AlSaif Gallery', 'معرض السيف', 'Consumer Discretionary Distribution & Retail'],
  ['NICE ONE', 'Nice One Beauty Digital', 'نايس ون للجمال الرقمي', 'Consumer Discretionary Distribution & Retail'],
  ['BUILD STATION', 'Build Station', 'بيلد ستيشن', 'Consumer Discretionary Distribution & Retail'],
  ['ALDREES', 'Aldrees Petroleum & Transport', 'الدريس للبترول والنقل', 'Consumer Discretionary Distribution & Retail'],
  ['CENOMI RETAIL', 'Cenomi Retail', 'سينومي ريتيل', 'Consumer Discretionary Distribution & Retail'],
  // Consumer Durables & Apparel
  ['NASEEJ', 'Naseej International Trading', 'ناسيج للتجارة الدولية', 'Consumer Durables & Apparel'],
  ['SIDC', 'Saudi Industrial Development', 'الصناعي السعودي للتطوير', 'Consumer Durables & Apparel'],
  ['ARTEX', 'Artex Company', 'آرتكس', 'Consumer Durables & Apparel'],
  ['LAZURDE', "Lazurde Company for Jewelry", 'لازوردي للمجوهرات', 'Consumer Durables & Apparel'],
  ['ALASEEL', 'Al Aseel Company', 'الأصيل', 'Consumer Durables & Apparel'],
  ['FITAIHI GROUP', 'Fitaihi Group Holding', 'مجموعة فتيحي القابضة', 'Consumer Durables & Apparel'],
  // Consumer Services
  ['SEERA', 'Seera Group Holding', 'مجموعة سيرا القابضة', 'Consumer Services'],
  ['BAAN', 'Baan Holding', 'بان القابضة', 'Consumer Services'],
  ['LEEJAM SPORTS', 'Leejam Sports Company', 'ليجام سبورتس', 'Consumer Services'],
  ['TECO', 'Tourism Enterprise Company', 'شركة التجارة والسياحة', 'Consumer Services'],
  ['ALKHALEEJ TRNG', 'AlKhaleej Training & Education', 'الخليج للتدريب والتعليم', 'Consumer Services'],
  ['NCLE', 'National Company for Learning', 'الشركة الوطنية للتعلم', 'Consumer Services'],
  ['ATAA', 'Ataa Educational Company', 'عطاء التعليمية', 'Consumer Services'],
  ['HERFY FOODS', 'Herfy Food Services', 'مطاعم هرفي', 'Consumer Services'],
  ['RAYDAN', 'Raydan Food Company', 'ريدان للأغذية', 'Consumer Services'],
  ['DWF', 'Dur Hospitality', 'ضور للضيافة', 'Consumer Services'],
  ['ALAMAR', 'Alamar Foods Company', 'الأمار للأغذية', 'Consumer Services'],
  ['AMERICANA', 'Americana Restaurants', 'أمريكانا ريستورنتس', 'Consumer Services'],
  ['BURGERIZZR', 'Burgerizzr Company', 'برجر إيزر', 'Consumer Services'],
  ['JAHEZ', 'Jahez International', 'جاهز الدولية', 'Consumer Services'],
  ['SPORT CLUBS', 'Sport Clubs Company', 'شركة الأندية الرياضية', 'Consumer Services'],
  ['ALMASAR ALSHAMIL', 'Almasar Alshamil Company', 'المسار الشامل', 'Consumer Services'],
  // Consumer Staples Distribution & Retail
  ['A.OTHAIM MARKET', 'Abdullah Al Othaim Markets', 'أسواق عبدالله العثيم', 'Consumer Staples Distribution & Retail'],
  ['FARM SUPERSTORES', 'Farm Superstores', 'أسواق المزرعة', 'Consumer Staples Distribution & Retail'],
  ['ANAAM HOLDING', 'Anaam International Holding', 'الأنعام الدولية القابضة', 'Consumer Staples Distribution & Retail'],
  ['THIMAR', 'Thimar Al Jazirah', 'ثمار الجزيرة', 'Consumer Staples Distribution & Retail'],
  ['BINDAWOOD', 'BinDawood Holding', 'بن داود القابضة', 'Consumer Staples Distribution & Retail'],
  ['ALMUNAJEM', 'Al Munajem Cold Stores', 'المنجم للمبردات', 'Consumer Staples Distribution & Retail'],
  ['ALDAWAA', 'Al Dawaa Medical Services', 'الدواء للخدمات الطبية', 'Consumer Staples Distribution & Retail'],
  ['NAHDI', 'Nahdi Medical', 'نهدي الطبية', 'Consumer Staples Distribution & Retail'],
  // Energy
  ['SARCO', 'Saudi Aramco Base Oil', 'شركة أرامكو السعودية لزيوت الأساس', 'Energy'],
  ['SAUDI ARAMCO', 'Saudi Aramco', 'أرامكو السعودية', 'Energy'],
  ['PETRO RABIGH', 'Petro Rabigh', 'بترو رابغ', 'Energy'],
  ['ARABIAN DRILLING', 'Arabian Drilling Company', 'شركة الحفر العربية', 'Energy'],
  ['ADES', 'ADES Holding', 'أدس القابضة', 'Energy'],
  ['BAHRI', 'Bahri (National Shipping)', 'البحري (الشحن الوطني)', 'Energy'],
  // Financial Services
  ['TADAWUL GROUP', 'Saudi Exchange (Tadawul)', 'مجموعة تداول السعودية', 'Financial Services'],
  ['AMLAK', 'Amlak International', 'أملاك الدولية', 'Financial Services'],
  ['SHL', 'Saudi Home Loans', 'التمويل العقاري السعودي', 'Financial Services'],
  ['SAIC', 'Saudi Arabia Insurance Company', 'الشركة السعودية للتأمين', 'Financial Services'],
  ['NAYIFAT', 'Nayifat Finance Company', 'نايفات للتمويل', 'Financial Services'],
  ['MRNA', 'Marn Company', 'مرن', 'Financial Services'],
  ['TASHEEL', 'Tasheel Finance', 'تسهيل للتمويل', 'Financial Services'],
  ['DERAYAH', 'Derayah Financial', 'دراية المالية', 'Financial Services'],
  ['SAUDI DARB', 'Saudi Darb Company', 'شركة درب السعودية', 'Financial Services'],
  ['KINGDOM', 'Kingdom Holding Company', 'شركة المملكة القابضة', 'Financial Services'],
  // Food & Beverages
  ['SAVOLA GROUP', 'Savola Group', 'مجموعة صافولا', 'Food & Beverages'],
  ['WAFRAH', 'Wafrah for Industry & Development', 'وفرة للصناعة والتطوير', 'Food & Beverages'],
  ['SADAFCO', 'Saudia Dairy & Foodstuff', 'شركة صافولا للألبان والأغذية', 'Food & Beverages'],
  ['ALMARAI', 'Almarai', 'المراعي', 'Food & Beverages'],
  ['TANMIAH', 'Tanmiah Food Company', 'تنمية الغذائية', 'Food & Beverages'],
  ['NAQI', 'Naqi Water Company', 'ناقي للمياه', 'Food & Beverages'],
  ['FIRST MILLS', 'First Milling Company', 'الشركة الأولى للطحن', 'Food & Beverages'],
  ['MODERN MILLS', 'Modern Mills for Food Products', 'مطاحن الحديثة للمنتجات الغذائية', 'Food & Beverages'],
  ['ARABIAN MILLS', 'Arabian Mills for Food Products', 'المطاحن العربية', 'Food & Beverages'],
  ['FOURTH MILLING', 'Fourth Milling Company', 'الشركة الرابعة للطحن', 'Food & Beverages'],
  ['ENTAJ', 'Entaj Company', 'الإنتاج', 'Food & Beverages'],
  ['NOFOTH', 'Nofoth Food Products', 'نفوذ للمنتجات الغذائية', 'Food & Beverages'],
  ['SINAD HOLDING', 'Sinad Holding', 'سناد القابضة', 'Food & Beverages'],
  ['HB', 'Halwani Brothers', 'إخوان حلواني', 'Food & Beverages'],
  ['NADEC', 'National Agricultural Development', 'التطوير الزراعي الوطني', 'Food & Beverages'],
  ['GACO', 'Gulf Agricultural Company', 'الشركة الخليجية للزراعة', 'Food & Beverages'],
  ['TADCO', 'Tabuk Agricultural Development', 'تبوك للتطوير الزراعي', 'Food & Beverages'],
  ['SFICO', 'Saudi Fisheries Company', 'الشركة السعودية للأسماك', 'Food & Beverages'],
  ['SHARQIYAH DEV', 'Eastern Province Development', 'تطوير المنطقة الشرقية', 'Food & Beverages'],
  ['ALJOUF', 'Al Jouf Agriculture Development', 'الجوف للتطوير الزراعي', 'Food & Beverages'],
  ['JAZADCO', 'Jazadco Company', 'جازادكو', 'Food & Beverages'],
  // Health Care Equipment & Svc
  ['AYYAN', 'Ayyan Company', 'عيان', 'Health Care Equipment & Svc'],
  ['CHEMICAL', 'Saudi Chemical Company', 'الشركة السعودية الكيميائية', 'Health Care Equipment & Svc'],
  ['MOUWASAT', 'Mouwasat Medical Services', 'المواساة للخدمات الطبية', 'Health Care Equipment & Svc'],
  ['DALLAH HEALTH', 'Dallah Healthcare', 'الرعاية الصحية دلة', 'Health Care Equipment & Svc'],
  ['CARE', 'Al Hammadi Company for Development', 'الحمادي للتطوير والاستثمار', 'Health Care Equipment & Svc'],
  ['ALHAMMADI', 'Al Hammadi Hospitals', 'مستشفيات الحمادي', 'Health Care Equipment & Svc'],
  ['SAUDI GERMAN HEALTH', 'Saudi German Health', 'الصحة الألمانية السعودية', 'Health Care Equipment & Svc'],
  ['SULAIMAN ALHABIB', 'Dr. Sulaiman Al Habib Medical', 'مجموعة د. سليمان الحبيب الطبية', 'Health Care Equipment & Svc'],
  ['EQUIPMENT HOUSE', 'Equipment House Company', 'بيت الأجهزة', 'Health Care Equipment & Svc'],
  ['FAKEEH CARE', 'Fakeeh Care Group', 'مجموعة فقيه للرعاية الصحية', 'Health Care Equipment & Svc'],
  ['ALMOOSA', 'Al Moosa Specialist Hospital', 'مستشفى الموسى التخصصي', 'Health Care Equipment & Svc'],
  ['SMC HEALTHCARE', 'SMC Healthcare', 'إس إم سي للرعاية الصحية', 'Health Care Equipment & Svc'],
  ['CMCER', 'Cancer Treatment Centers', 'مراكز معالجة السرطان', 'Health Care Equipment & Svc'],
  // Household & Personal Products
  ['ALMAJED OUD', 'Almajed Oud Company', 'المجد للعود', 'Household & Personal Products'],
  // Insurance
  ['TAWUNIYA', 'Tawuniya', 'التعاونية للتأمين', 'Insurance'],
  ['JAZIRA TAKAFUL', 'Bank AlJazira Takaful Taawuni', 'بنك الجزيرة تكافل تعاوني', 'Insurance'],
  ['MALATH INSURANCE', 'Malath Insurance & Reinsurance', 'ملاذ للتأمين وإعادة التأمين', 'Insurance'],
  ['MEDGULF', 'MedGulf Insurance', 'الخليج للتأمين الطبي', 'Insurance'],
  ['MUTAKAMELA', 'Mutakamela Insurance', 'متكاملة للتأمين التعاوني', 'Insurance'],
  ['SALAMA', 'Islamic Arab Insurance (Salama)', 'الإسلامية العربية للتأمين', 'Insurance'],
  ['WALAA', 'Walaa Cooperative Insurance', 'ولاء للتأمين التعاوني', 'Insurance'],
  ['ARABIAN SHIELD', 'Arabian Shield Cooperative Insurance', 'الدرع العربي للتأمين التعاوني', 'Insurance'],
  ['SAICO', 'Saudi Arabian Cooperative Insurance', 'التأمين التعاوني السعودي', 'Insurance'],
  ['GULF UNION ALAHLIA', 'Gulf Union Alahlia Cooperative Insurance', 'الخليج أهلية للتأمين', 'Insurance'],
  ['ACIG', 'Arabian Company for Insurance & Reinsurance', 'الشركة العربية للتأمين وإعادة التأمين', 'Insurance'],
  ['AICC', 'Al Ahlia Insurance Company', 'الأهلية للتأمين التعاوني', 'Insurance'],
  ['ALETIHAD', 'Al Etihad Cooperative Insurance', 'الاتحاد للتأمين التعاوني', 'Insurance'],
  ['ALSAGR INSURANCE', 'Al Sagr National Insurance', 'الصقر للتأمين الوطني', 'Insurance'],
  ['UCA', 'United Cooperative Assurance', 'التعاونية المتحدة للتأمين', 'Insurance'],
  ['SAUDI RE', 'Saudi Reinsurance Company', 'شركة إعادة التأمين السعودية', 'Insurance'],
  ['BUPA ARABIA', 'Bupa Arabia', 'بوبا العربية للتأمين', 'Insurance'],
  ['ALRAJHI TAKAFUL', 'Al Rajhi Takaful', 'الراجحي للتكافل', 'Insurance'],
  ['CHUBB', 'Chubb Arabia Cooperative Insurance', 'شوب العربية للتأمين التعاوني', 'Insurance'],
  ['GIG', 'GIG Gulf', 'جيج الخليج', 'Insurance'],
  ['GULF GENERAL', 'Gulf General Cooperative Insurance', 'الخليج العام للتأمين التعاوني', 'Insurance'],
  ['LIVA', 'Liva Insurance Company', 'ليفا للتأمين', 'Insurance'],
  ['WATANIYA', 'Wataniya Insurance', 'الوطنية للتأمين', 'Insurance'],
  ['AMANA INSURANCE', 'Amana Cooperative Insurance', 'أمانة للتأمين التعاوني', 'Insurance'],
  ['ENAYA', 'Enaya Cooperative Insurance', 'عناية للتأمين التعاوني', 'Insurance'],
  ['RASAN', 'Rasan Information Technology', 'رسن لتقنية المعلومات', 'Insurance'],
  // Materials
  ['TAKWEEN', 'Takween Advanced Industries', 'تكوين للصناعات المتقدمة', 'Materials'],
  ['MEPCO', 'Middle East Paper Company', 'الشركة الأوسطية للورق', 'Materials'],
  ['BCI', 'Basic Chemical Industries', 'الصناعات الكيميائية الأساسية', 'Materials'],
  ['MAADEN', "Ma'aden (Saudi Arabian Mining)", 'معادن (شركة التعدين العربية السعودية)', 'Materials'],
  ['ASLAK', 'Aslak Company', 'أسلاك', 'Materials'],
  ['ALYAMAMAH STEEL', 'Alyamamah Steel Industries', 'اليمامة للصلب', 'Materials'],
  ['SSP', 'Saudi Steel Pipe', 'الأنابيب الفولاذية السعودية', 'Materials'],
  ['EAST PIPES', 'East Pipes Integrated Company', 'الشرقية للأنابيب المتكاملة', 'Materials'],
  ['AMAK', 'Arabian Marble Company', 'الرخام العربي', 'Materials'],
  ['UCIC', 'United Carton Industries', 'الصناعات الكرتونية المتحدة', 'Materials'],
  ['SALEH ALRASHED', 'Saleh Al Rashed & Sons', 'صالح الراشد وأبناؤه', 'Materials'],
  ['CHEMANOL', 'Methanol Chemicals Company', 'شركة كيمانول للميثانول', 'Materials'],
  ['SABIC', 'SABIC', 'سابك', 'Materials'],
  ['SABIC AGRI-NUTRIENTS', 'SABIC Agri-Nutrients', 'سابك للمغذيات الزراعية', 'Materials'],
  ['TASNEE', 'National Industrialization Company', 'الشركة الوطنية للصناعة', 'Materials'],
  ['NGC', 'National Gas & Industrialization', 'الوطنية للغاز والتصنيع', 'Materials'],
  ['ZOUJAJ', 'Saudi Arabian Amiantit (Zoujaj)', 'الزجاج السعودي', 'Materials'],
  ['ALUJAIN', 'Alujain Corporation', 'العجين للبتروكيماويات', 'Materials'],
  ['FIPCO', 'Filling & Packing Materials Manufacturing', 'التعبئة والتغليف والمواد التصنيعية', 'Materials'],
  ['APC', 'Arabian Pipes Company', 'الأنابيب العربية', 'Materials'],
  ['NAMA CHEMICALS', 'Nama Chemicals', 'نامة للكيماويات', 'Materials'],
  ['MAADANIYAH', 'Saudi Vitrified Clay Pipe', 'الفخارية المدانية السعودية', 'Materials'],
  ['LUBEREF', 'Saudi Aramco Base Oil (Luberef)', 'لوبريف لزيوت التشحيم', 'Materials'],
  ['SENAAT', 'General Industry Corporation', 'الشركة العامة للصناعات', 'Materials'],
  ['SIIG', 'Saudi Industrial Investment Group', 'مجموعة الاستثمار الصناعي السعودي', 'Materials'],
  ['YANSAB', 'Yanbu National Petrochemical', 'ينساب للبتروكيماويات', 'Materials'],
  ['SPM', 'Saudi Paper Manufacturing', 'الشركة السعودية للورق', 'Materials'],
  ['SIPCHEM', 'Saudi International Petrochemical', 'الشركة الدولية للبتروكيماويات', 'Materials'],
  ['ADVANCED', 'Advanced Petrochemical Company', 'الشركة المتقدمة للبتروكيماويات', 'Materials'],
  ['SAUDI KAYAN', 'Saudi Kayan Petrochemical', 'سعودي كيان للبتروكيماويات', 'Materials'],
  ['SVCP', 'Saudi Vitrified Clay Pipe', 'الأنابيب السعودية المصهورة', 'Materials'],
  ['NAJRAN CEMENT', 'Najran Cement Company', 'شركة أسمنت نجران', 'Materials'],
  ['CITY CEMENT', 'City Cement Company', 'شركة أسمنت المدينة', 'Materials'],
  ['NORTHERN CEMENT', 'Northern Region Cement Company', 'أسمنت المنطقة الشمالية', 'Materials'],
  ['UACC', 'United Arab Cement Company', 'الشركة العربية المتحدة للأسمنت', 'Materials'],
  ['OASIS', 'Oasis Company for Real Estate Dev', 'الواحة للتطوير العقاري', 'Materials'],
  ['ALKATHIRI', 'Al Kathiri Holding Company', 'الكثيري القابضة', 'Materials'],
  ['ACC', 'Arabian Cement Company', 'الشركة العربية للأسمنت', 'Materials'],
  ['YC', 'Yamama Cement Company', 'يمامة للأسمنت', 'Materials'],
  ['SAUDI CEMENT', 'Saudi Cement Company', 'الشركة السعودية للأسمنت', 'Materials'],
  ['QACCO', 'Al Qassim Cement Company', 'أسمنت القصيم', 'Materials'],
  ['SPCC', 'Southern Province Cement Company', 'أسمنت المنطقة الجنوبية', 'Materials'],
  ['YCC', 'Yanbu Cement Company', 'أسمنت ينبع', 'Materials'],
  ['EPCCO', 'Eastern Province Cement Company', 'أسمنت المنطقة الشرقية', 'Materials'],
  ['TCC', 'Tabuk Cement Company', 'أسمنت تبوك', 'Materials'],
  ['JOUF CEMENT', 'Jouf Cement Company', 'أسمنت الجوف', 'Materials'],
  ['RIYADH CEMENT', 'Riyadh Cement Company', 'أسمنت الرياض', 'Materials'],
  ['TALCO', 'Qassim Cement (Talco)', 'طلكو للأسمنت', 'Materials'],
  // Media and Entertainment
  ['TAPRCO', 'Tapco Company', 'تابركو', 'Media and Entertainment'],
  ['ALARABIA', 'Al Arabiya News Channel', 'قناة العربية الإخبارية', 'Media and Entertainment'],
  ['MBC GROUP', 'MBC Group', 'مجموعة MBC', 'Media and Entertainment'],
  ['SRMG', 'Saudi Research and Media Group', 'المجموعة السعودية للأبحاث والإعلام', 'Media and Entertainment'],
  // Pharma, Biotech & Life Sciences
  ['SPIMACO', 'Saudi Pharmaceutical Industries', 'سبيماكو للصناعات الدوائية', 'Pharma, Biotech & Life Sciences'],
  ['JAMJOOM PHARMA', 'Jamjoom Pharmaceuticals', 'جمجوم للأدوية', 'Pharma, Biotech & Life Sciences'],
  ['AVALON PHARMA', 'Avalon Pharma', 'أفالون فارما', 'Pharma, Biotech & Life Sciences'],
  // REITs
  ['RIYAD REIT', 'Riyad REIT Fund', 'صندوق الرياض ريت', 'REITs'],
  ['ALJAZIRA REIT', 'AlJazira REIT Fund', 'صندوق الجزيرة ريت', 'REITs'],
  ['JADWA REIT ALHARAMAIN', 'Jadwa REIT Alharamain Fund', 'صندوق جدوى ريت الحرمين', 'REITs'],
  ['TALEEM REIT', 'Taleem REIT Fund', 'صندوق تعليم ريت', 'REITs'],
  ['AL MAATHER REIT', 'Al Maather REIT Fund', 'صندوق المعذر ريت', 'REITs'],
  ['MUSHARAKA REIT', 'Musharaka REIT Fund', 'صندوق مشاركة ريت', 'REITs'],
  ['MULKIA REIT', 'Mulkia REIT Fund', 'صندوق ملكية ريت', 'REITs'],
  ['AL AZIZIAH REIT', 'Al Aziziah REIT Fund', 'صندوق العزيزية ريت', 'REITs'],
  ['ALAHLI REIT 1', 'AlAhli REIT Fund 1', 'صندوق الأهلي ريت 1', 'REITs'],
  ['DERAYAH REIT', 'Derayah REIT Fund', 'صندوق دراية ريت', 'REITs'],
  ['AL RAJHI REIT', 'Al Rajhi REIT Fund', 'صندوق الراجحي ريت', 'REITs'],
  ['JADWA REIT SAUDI', 'Jadwa REIT Saudi Fund', 'صندوق جدوى ريت السعودي', 'REITs'],
  ['SEDCO CAPITAL REIT', 'Sedco Capital REIT Fund', 'صندوق سدكو كابيتال ريت', 'REITs'],
  ['ALINMA RETAIL REIT', 'Alinma Retail REIT Fund', 'صندوق إنماء ريت التجزئة', 'REITs'],
  ['MEFIC REIT', 'MEFIC REIT Fund', 'صندوق مفيك ريت', 'REITs'],
  ['BONYAN REIT', 'Bonyan REIT Fund', 'صندوق بنيان ريت', 'REITs'],
  ['ALKHABEER REIT', 'AlKhabeer REIT Fund', 'صندوق الخبير ريت', 'REITs'],
  ['ALINMA HOSPITALITY REIT', 'Alinma Hospitality REIT Fund', 'صندوق إنماء ريت الضيافة', 'REITs'],
  ['ALISTITHMAR REIT', 'Alistithmar REIT Fund', 'صندوق الاستثمار ريت', 'REITs'],
  // Real Estate Mgmt & Dev't
  ['ALAKARIA', 'Al Akaria (Saudi Real Estate)', 'العقارية السعودية', "Real Estate Mgmt & Dev't"],
  ['TAIBA', 'Taiba Investments', 'طيبة للاستثمار', "Real Estate Mgmt & Dev't"],
  ['MCDC', 'Mecca Commercial & Development', 'مكة التجارية والتطوير', "Real Estate Mgmt & Dev't"],
  ['ARDCO', 'Arriyadh Development Company', 'شركة الرياض للتطوير', "Real Estate Mgmt & Dev't"],
  ['EMAAR EC', 'Emaar the Economic City', 'إعمار للمدينة الاقتصادية', "Real Estate Mgmt & Dev't"],
  ['RED SEA', 'Red Sea International', 'البحر الأحمر الدولية', "Real Estate Mgmt & Dev't"],
  ['JABAL OMAR', 'Jabal Omar Development', 'جبل عمر للتطوير', "Real Estate Mgmt & Dev't"],
  ['DAR ALARKAN', 'Dar Al Arkan Real Estate', 'دار الأركان للتطوير العقاري', "Real Estate Mgmt & Dev't"],
  ['KEC', 'Knowledge Economic City', 'مدينة المعرفة الاقتصادية', "Real Estate Mgmt & Dev't"],
  ['ALANDALUS', 'Alandalus Property Company', 'الأندلس العقارية', "Real Estate Mgmt & Dev't"],
  ['CENOMI CENTERS', 'Cenomi Centers', 'سينومي سنترز', "Real Estate Mgmt & Dev't"],
  ['RETAL', 'Retal Urban Development', 'ريتال للتطوير العمراني', "Real Estate Mgmt & Dev't"],
  ['SUMOU', 'Sumou Real Estate', 'سمو للعقارات', "Real Estate Mgmt & Dev't"],
  ['BANAN', 'Banan Real Estate', 'بنان للعقارات', "Real Estate Mgmt & Dev't"],
  ['MASAR', 'Masar Company', 'مسار', "Real Estate Mgmt & Dev't"],
  ['ALMAJDIAH', 'Al Majdiah Real Estate', 'المجدية للعقارات', "Real Estate Mgmt & Dev't"],
  ['ALRAMZ', 'Al Ramz Corporation', 'الرمز للاستثمار والتطوير', "Real Estate Mgmt & Dev't"],
  // Software & Services
  ['MIS', 'Mawarid Information Systems', 'موارد لنظم المعلومات', 'Software & Services'],
  ['ARAB SEA', 'Arab Sea Information Systems', 'البحر العربي لنظم المعلومات', 'Software & Services'],
  ['SOLUTIONS', 'Solutions by stc', 'سوليوشنز باي إس تي سي', 'Software & Services'],
  ['ELM', 'Elm Company', 'شركة علم', 'Software & Services'],
  ['2P', 'Planning & Procurement Company', 'التخطيط والمشتريات', 'Software & Services'],
  ['DBS', 'Digital Business Solutions', 'الحلول الرقمية للأعمال', 'Software & Services'],
  ['AZM', 'Azm & Saad Group', 'عزم وسعد المجموعة', 'Software & Services'],
  // Telecommunication Services
  ['STC', 'Saudi Telecom Company (stc)', 'شركة الاتصالات السعودية', 'Telecommunication Services'],
  ['ETIHAD ETISALAT', 'Mobily (Etihad Etisalat)', 'موبايلي (اتحاد اتصالات)', 'Telecommunication Services'],
  ['ZAIN KSA', 'Zain Saudi Arabia', 'زين السعودية', 'Telecommunication Services'],
  ['GO TELECOM', 'Go Telecom', 'جو اتصال', 'Telecommunication Services'],
  // Transportation
  ['SISCO HOLDING', 'Saudi Industrial Services Company', 'الشركة السعودية للخدمات الصناعية', 'Transportation'],
  ['SGS', 'Al Saghyir Group', 'مجموعة الصغير', 'Transportation'],
  ['SAPTCO', 'Saudi Public Transport Company', 'الشركة السعودية لتقنية المعلومات', 'Transportation'],
  ['BUDGET SAUDI', 'Budget Saudi', 'بدجت السعودية', 'Transportation'],
  ['THEEB', 'Theeb Rent a Car', 'ذيب لتأجير السيارات', 'Transportation'],
  ['LUMI', 'Lumi', 'لومي', 'Transportation'],
  ['SAL', 'Saudi Logistics Services', 'سال السعودية للخدمات اللوجستية', 'Transportation'],
  ['FLYNAS', 'Flynas', 'فلاي ناس', 'Transportation'],
  ['CHERRY', 'Cherry Company', 'شيري', 'Transportation'],
  // Utilities
  ['GASCO', 'Saudi Gas Company', 'شركة الغاز السعودية', 'Utilities'],
  ['AWPT', 'Arabian Water and Power Projects', 'مشاريع المياه والطاقة العربية', 'Utilities'],
  ['ACWA', 'ACWA Power', 'أكوا باور', 'Utilities'],
  ['MARAFIQ', 'Marafiq', 'مرافق', 'Utilities'],
  ['MIAHONA', 'Miahona Company', 'مياهنا', 'Utilities'],
  ['SAUDI ENERGY', 'Saudi Energy Ventures', 'المشاريع الطاقوية السعودية', 'Utilities'],
];

export const MOCK_COMPANIES: MockCompany[] = RAW.map(([ticker, name_en, name_ar, sector]) => ({
  id: `mock-${ticker.toLowerCase().replace(/\s+/g, '-')}`,
  name_en,
  name_ar,
  sector,
  ticker,
  logo_url: logoUrl(ticker),
  reports: placeholderReports(ticker.toLowerCase().replace(/\s+/g, '-')),
}));
